config/routes.rb
Rails.application.routes.draw do
  post 'user_token' => 'user_token#create'
  get '/user/whatsmyid' => 'users#id'
  resources :users
  resources :friends
  resources :chatrooms
  resources :chatroom_users
  resources :chatroom_messages
  
  get '/read_people' => 'friends#read_people'
  get '/profile/:id' => 'friends#read_profile'
  get '/feed/:id' => 'friends#feed'
  post '/follow' => 'friends#follow_user'
  post '/unfollow' => 'friends#unfollow_user'

  get '/chatrooms' => 'chatroom#read_chatrooms'
  get '/chatroom/:id' => 'chatroom#read_chatroom'



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
    belongs_to :user
    has_many :chatroom_users
    has_many :chatroom_messages
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
    skip_before_action :verify_authenticity_token
    protect_from_forgery with: :null_session
    before_action :authenticate_user

    def read_chatrooms
        userid = 1
        chatrooms = Chatroom.where(user_id: userid)
        render json: chatrooms
    end

    def read_chatroom
        userid = 1
        chatrooms = Chatroom.where(user_id: userid)
        room_id = params[:id]
        room_info = Chatroom.find_by :id => room_id
        room_participants = ChatroomUser.where(chatroom_id: room_id)
        room_participants_detail = []
        room_participants.each do |user| 
            room_participants_detail.push(User.find_by :id => user.id)
        end
        room_messages = ChatroomMessage.where(chatroom_id: room_id)
        @query = {
            "chatrooms": chatrooms,
            "info": room_info, 
            "users": room_participants_detail, 
            "messages": room_messages,
        }
        render json: @query
    end

end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  skip_before_action :verify_authenticity_token
  protect_from_forgery with: :null_session
  before_action :authenticate_user
  before_action :set_chatroom, only: [:show, :edit, :update, :destroy]

  # GET /chatrooms
  # GET /chatrooms.json
  def index
    @chatrooms = Chatroom.all
  end

  # GET /chatrooms/1
  # GET /chatrooms/1.json
  def show
  end

  # GET /chatrooms/new
  def new
    @chatroom = Chatroom.new
  end

  # GET /chatrooms/1/edit
  def edit
  end

  # POST /chatrooms
  # POST /chatrooms.json
  def create
    @chatroom = Chatroom.new(chatroom_params)

    respond_to do |format|
      if @chatroom.save
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully created.' }
        format.json { render :show, status: :created, location: @chatroom }
      else
        format.html { render :new }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chatrooms/1
  # PATCH/PUT /chatrooms/1.json
  def update
    respond_to do |format|
      if @chatroom.update(chatroom_params)
        format.html { redirect_to @chatroom, notice: 'Chatroom was successfully updated.' }
        format.json { render :show, status: :ok, location: @chatroom }
      else
        format.html { render :edit }
        format.json { render json: @chatroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chatrooms/1
  # DELETE /chatrooms/1.json
  def destroy
    @chatroom.destroy
    respond_to do |format|
      format.html { redirect_to chatrooms_url, notice: 'Chatroom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chatroom
      @chatroom = Chatroom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chatroom_params
      params.require(:chatroom).permit(:user_id, :room_name)
    end
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/views/chatrooms/_form.html.erb
<%= form_with(model: chatroom, local: true) do |form| %>
  <% if chatroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chatroom.errors.count, "error") %> prohibited this chatroom from being saved:</h2>

      <ul>
        <% chatroom.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :room_name %>
    <%= form.text_field :room_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/chatrooms/edit.html.erb
<h1>Editing Chatroom</h1>

<%= render 'form', chatroom: @chatroom %>

<%= link_to 'Show', @chatroom %> |
<%= link_to 'Back', chatrooms_path %>

app/views/chatrooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Chatrooms</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Room name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chatrooms.each do |chatroom| %>
      <tr>
        <td><%= chatroom.user_id %></td>
        <td><%= chatroom.room_name %></td>
        <td><%= link_to 'Show', chatroom %></td>
        <td><%= link_to 'Edit', edit_chatroom_path(chatroom) %></td>
        <td><%= link_to 'Destroy', chatroom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chatroom', new_chatroom_path %>

app/views/chatrooms/new.html.erb
<h1>New Chatroom</h1>

<%= render 'form', chatroom: @chatroom %>

<%= link_to 'Back', chatrooms_path %>

app/views/chatrooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @chatroom.user_id %>
</p>

<p>
  <strong>Room name:</strong>
  <%= @chatroom.room_name %>
</p>

<%= link_to 'Edit', edit_chatroom_path(@chatroom) %> |
<%= link_to 'Back', chatrooms_path %>